import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Clock, Globe2 } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/AppShell";
import { CategoryBadge } from "@/components/CategoryBadge";
import { Button } from "@/components/ui/button";
import { courseCategories, courses, learningPaths } from "@/data/mockLearning";
import { text } from "@/data/mockNews";
import { useApp } from "@/contexts/AppContext";
export const Route=createFileRoute("/courses")({head:()=>({meta:[{title:"Free Courses & Learning Paths — NOVA AI"},{name:"description",content:"Curated free courses and structured learning paths for AI and technology."},{property:"og:title",content:"Free Courses — NOVA AI"},{property:"og:description",content:"Build practical AI and technology skills with curated free learning."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:CoursesPage});
function CoursesPage(){const {language}=useApp();const ar=language==="ar";const [category,setCategory]=useState("All");const filtered=category==="All"?courses:courses.filter(c=>c.category.en===category);return <AppShell><div className="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-10"><header className="border-b border-border pb-7"><p className="text-xs font-bold uppercase text-primary">{ar?"أكاديمية NOVA":"NOVA Academy"}</p><h1 className="mt-2 text-4xl font-extrabold sm:text-5xl">{ar?"الدورات المجانية":"Free Courses"}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{ar?"موارد عالية الجودة ومسارات واضحة لبناء مهارات تقنية عملية.":"High-quality resources and clear paths for building practical technology skills."}</p></header><section className="mt-8"><h2 className="text-xl font-bold">{ar?"تعلم موصى به":"Recommended Learning"}</h2><div className="mt-4 grid gap-5 lg:grid-cols-2">{courses.filter(c=>c.featured).map(c=><CourseCard key={c.id} course={c} featured/>)}</div></section><div className="mt-10 flex flex-wrap gap-2">{courseCategories.map(c=><Button key={c.en} variant={category===c.en?"default":"outline"} size="sm" onClick={()=>setCategory(c.en)}>{text(c,language)}</Button>)}</div><div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><CourseCard key={c.id} course={c}/>)}</div><section className="mt-14 border-t border-border pt-10"><p className="text-xs font-bold uppercase text-primary">{ar?"تقدم خطوة بخطوة":"Progress step by step"}</p><h2 className="mt-2 text-3xl font-bold">{ar?"المسارات التعليمية":"Learning Paths"}</h2><div className="mt-6 grid gap-5 lg:grid-cols-2">{learningPaths.map(path=><div key={path.title.en} className="border border-border bg-card p-6 shadow-card"><h3 className="text-xl font-bold">{text(path.title,language)}</h3><div className="mt-6 grid grid-cols-1 gap-2 sm:grid-cols-4">{path.steps.map((step,i)=><div key={step.en} className="relative flex items-center gap-2 sm:block"><span className="grid h-7 w-7 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">{i+1}</span><p className="mt-2 text-sm font-semibold">{text(step,language)}</p>{i<path.steps.length-1&&<ArrowRight className={`hidden h-4 w-4 text-muted-foreground sm:absolute sm:top-2 sm:block ${ar?"-start-3 rotate-180":"-end-3"}`}/>}</div>)}</div></div>)}</div></section></div></AppShell>}
function CourseCard({course,featured=false}:{course:(typeof courses)[number];featured?:boolean}){const {language}=useApp();const ar=language==="ar";return <article className={`overflow-hidden border border-border bg-card shadow-card ${featured?"grid sm:grid-cols-[220px_minmax(0,1fr)]":""}`}><img src={course.image} alt="" className={`w-full object-cover ${featured?"h-full min-h-48":"aspect-[16/9]"}`}/><div className="p-5"><div className="flex items-center justify-between gap-3"><CategoryBadge>{text(course.category,language)}</CategoryBadge><span className="rounded-full bg-signal/15 px-2.5 py-1 text-[10px] font-black text-signal">FREE</span></div><h3 className="mt-4 text-xl font-bold">{text(course.title,language)}</h3><p className="mt-1 text-sm font-semibold text-muted-foreground">{course.platform}</p><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1"><CheckCircle2 className="h-3.5 w-3.5"/>{text(course.level,language)}</span><span className="flex items-center gap-1"><Clock className="h-3.5 w-3.5"/>{text(course.duration,language)}</span><span className="flex items-center gap-1"><Globe2 className="h-3.5 w-3.5"/>{text(course.language,language)}</span></div><Button asChild className="mt-5 w-full"><a href={course.url} target="_blank" rel="noreferrer">{ar?"عرض الدورة":"View Course"}</a></Button></div></article>}
