import { createFileRoute } from "@tanstack/react-router";
import { Bookmark, CalendarDays, MapPin, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { opportunities, opportunityCategories } from "@/data/mockOpportunities";
import { text } from "@/data/mockNews";
import { useApp } from "@/contexts/AppContext";
export const Route=createFileRoute("/opportunities")({head:()=>({meta:[{title:"Opportunities — NOVA AI"},{name:"description",content:"Curated AI scholarships, internships, competitions, fellowships and research opportunities."},{property:"og:title",content:"Opportunities — NOVA AI"},{property:"og:description",content:"Find your next AI scholarship, fellowship, internship or challenge."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:OpportunitiesPage});
function OpportunitiesPage(){const {language}=useApp();const ar=language==="ar";const [category,setCategory]=useState("All");const [saved,setSaved]=useState<Set<string>>(new Set());const filtered=category==="All"?opportunities:opportunities.filter(o=>o.category.en===category);const toggle=(id:string)=>{setSaved(current=>{const next=new Set(current);const removing=next.has(id);removing?next.delete(id):next.add(id);toast.success(ar?(removing?"تمت إزالة الفرصة":"تم حفظ الفرصة"):(removing?"Opportunity removed":"Opportunity saved"));return next})};return <AppShell><div className="mx-auto max-w-[1400px] px-4 py-8 sm:px-6 lg:px-10"><header className="border-b border-border pb-7"><p className="text-xs font-bold uppercase text-primary">{ar?"خطوتك القادمة":"Your next move"}</p><h1 className="mt-2 text-4xl font-extrabold sm:text-5xl">{ar?"الفرص":"Opportunities"}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{ar?"منح وتدريب ومسابقات وفرص بحثية مختارة بعناية.":"Curated scholarships, internships, challenges and research programs worth your time."}</p></header><div className="mt-8 flex flex-wrap gap-2">{opportunityCategories.map(c=><Button key={c.en} variant={category===c.en?"default":"outline"} size="sm" onClick={()=>setCategory(c.en)}>{text(c,language)}</Button>)}</div><div className="mt-7 grid gap-5 lg:grid-cols-2">{filtered.map(o=>{const status={open:ar?"مفتوح":"Open",soon:ar?"يغلق قريبًا":"Closing Soon",upcoming:ar?"قريبًا":"Upcoming"}[o.status];return <article key={o.id} className="flex flex-col border border-border bg-card p-6 shadow-card"><div className="flex items-start justify-between gap-4"><div><span className="text-[10px] font-bold uppercase text-primary">{text(o.category,language)}</span><h2 className="mt-2 text-xl font-bold">{text(o.title,language)}</h2><p className="mt-1 text-sm font-semibold text-muted-foreground">{o.organization}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-bold ${o.status==="soon"?"bg-destructive/10 text-destructive":o.status==="open"?"bg-signal/15 text-signal":"bg-primary-soft text-primary"}`}>{status}</span></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{text(o.description,language)}</p><div className="mt-5 grid gap-3 text-xs sm:grid-cols-3"><span className="flex items-start gap-2"><MapPin className="h-4 w-4 text-primary"/>{text(o.location,language)}</span><span className="flex items-start gap-2"><Users className="h-4 w-4 text-primary"/>{text(o.eligibility,language)}</span><span className="flex items-start gap-2"><CalendarDays className="h-4 w-4 text-primary"/>{text(o.deadline,language)}</span></div><div className="mt-6 flex gap-2 border-t border-border pt-4"><Button className="flex-1">{ar?"عرض الفرصة":"View Opportunity"}</Button><Button variant="outline" onClick={()=>toggle(o.id)}><Bookmark className={saved.has(o.id)?"fill-current":""}/>{ar?"حفظ":"Save"}</Button></div></article>})}</div></div></AppShell>}
