"""Core schema: content, taxonomy, AI outputs, users, briefs and operations.

Creates the 27 NOVA tables described in DATABASE.md. Besides the tables
(generated from the models) this migration:

* enables the ``vector`` (pgvector) and ``pg_trgm`` extensions — in Supabase's
  ``extensions`` schema when it exists, otherwise in the default schema;
* adds a trigger to every table with ``updated_at`` so the timestamp is
  maintained even for edits made outside the API;
* enables Row-Level Security on every table. The backend connects as the table
  owner and is unaffected; roles used by Supabase's public data API get no
  access (defense in depth — the ``app`` schema is not exposed anyway).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 19:02:07.790818+00:00
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


EXTENSIONS = ("vector", "pg_trgm")


def _create_extensions() -> None:
    for name in EXTENSIONS:  # constant names, not user input
        op.execute(
            f"""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'extensions') THEN
                    CREATE EXTENSION IF NOT EXISTS {name} WITH SCHEMA extensions;
                ELSE
                    CREATE EXTENSION IF NOT EXISTS {name};
                END IF;
            END
            $$;
            """  # noqa: S608 - constant extension names
        )


def _add_updated_at_triggers_and_rls() -> None:
    op.execute(
        """
        DO $$
        DECLARE
            tbl record;
        BEGIN
            FOR tbl IN
                SELECT c.relname
                FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'app' AND c.relkind = 'r' AND c.relname <> 'alembic_version'
            LOOP
                EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY', tbl.relname);
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'app' AND table_name = tbl.relname
                      AND column_name = 'updated_at'
                ) THEN
                    EXECUTE format(
                        'CREATE TRIGGER %I BEFORE UPDATE ON app.%I '
                        'FOR EACH ROW EXECUTE FUNCTION app.set_updated_at()',
                        'trg_' || tbl.relname || '_updated_at', tbl.relname
                    );
                END IF;
            END LOOP;
        END
        $$;
        """
    )


def upgrade() -> None:
    _create_extensions()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_ar", sa.String(length=200), nullable=True),
        sa.Column("affiliation", sa.String(length=300), nullable=True),
        sa.Column("orcid", sa.String(length=19), nullable=True),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("orcid", name=op.f("uq_authors_orcid")),
        sa.UniqueConstraint("slug", name=op.f("uq_authors_slug")),
        schema="app",
    )
    op.create_table(
        "categories",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("name_ar", sa.String(length=120), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("description_ar", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("content_type", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_type IN ('article', 'paper', 'course', 'opportunity', 'tool')",
            name=op.f("ck_categories_content_type"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["app.categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_categories_parent_id"), "categories", ["parent_id"], unique=False, schema="app"
    )
    op.create_index(
        "ix_categories_type_sort",
        "categories",
        ["content_type", "sort_order"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "learning_paths",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title_en", sa.String(length=200), nullable=False),
        sa.Column("title_ar", sa.String(length=200), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("description_ar", sa.Text(), nullable=True),
        sa.Column("level", sa.String(length=32), server_default="all_levels", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('beginner', 'intermediate', 'advanced', 'all_levels')",
            name=op.f("ck_learning_paths_course_level"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_paths")),
        sa.UniqueConstraint("slug", name=op.f("uq_learning_paths_slug")),
        schema="app",
    )
    op.create_table(
        "sources",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("feed_url", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=32), server_default="en", nullable=False),
        sa.Column("trust_level", sa.SmallInteger(), server_default="3", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("fetch_interval_minutes", sa.Integer(), server_default="60", nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('rss', 'arxiv', 'api', 'job_board', 'website', 'manual')",
            name=op.f("ck_sources_source_kind"),
        ),
        sa.CheckConstraint("language IN ('en', 'ar')", name=op.f("ck_sources_language")),
        sa.CheckConstraint(
            "consecutive_failures >= 0", name=op.f("ck_sources_consecutive_failures_nonneg")
        ),
        sa.CheckConstraint(
            "fetch_interval_minutes >= 5", name=op.f("ck_sources_fetch_interval_min")
        ),
        sa.CheckConstraint(
            "trust_level BETWEEN 1 AND 5", name=op.f("ck_sources_trust_level_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("feed_url", name=op.f("uq_sources_feed_url")),
        sa.UniqueConstraint("slug", name=op.f("uq_sources_slug")),
        schema="app",
    )
    op.create_index(
        "ix_sources_active_kind", "sources", ["is_active", "kind"], unique=False, schema="app"
    )
    op.create_table(
        "tags",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=False),
        sa.Column("name_ar", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("slug", name=op.f("uq_tags_slug")),
        schema="app",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=32), server_default="user", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('user', 'editor', 'admin')", name=op.f("ck_users_user_role")),
        sa.CheckConstraint(
            "status IN ('active', 'suspended', 'deleted')", name=op.f("ck_users_user_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="app",
    )
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
        schema="app",
    )
    op.create_table(
        "collection_jobs",
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="queued", nullable=False),
        sa.Column("trigger", sa.String(length=32), server_default="schedule", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_found", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_created", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_updated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("items_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_collection_jobs_job_status"),
        ),
        sa.CheckConstraint(
            "trigger IN ('schedule', 'manual', 'retry')",
            name=op.f("ck_collection_jobs_job_trigger"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_collection_jobs_times_order"),
        ),
        sa.CheckConstraint(
            "items_found >= 0 AND items_created >= 0 AND items_updated >= 0 AND items_failed >= 0",
            name=op.f("ck_collection_jobs_counts_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["app.sources.id"],
            name=op.f("fk_collection_jobs_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_jobs")),
        schema="app",
    )
    op.create_index(
        "ix_collection_jobs_source_recent",
        "collection_jobs",
        ["source_id", sa.literal_column("created_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_collection_jobs_status_recent",
        "collection_jobs",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_table(
        "content_items",
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="draft", nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("original_language", sa.String(length=32), server_default="en", nullable=False),
        sa.Column("title_en", sa.Text(), nullable=True),
        sa.Column("title_ar", sa.Text(), nullable=True),
        sa.Column("summary_en", sa.Text(), nullable=True),
        sa.Column("summary_ar", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("url_hash", sa.String(length=64), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("importance", sa.SmallInteger(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_trending", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("trending_score", sa.Float(), server_default="0", nullable=False),
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ai_generated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_type IN ('article', 'paper', 'course', 'opportunity', 'tool')",
            name=op.f("ck_content_items_content_type"),
        ),
        sa.CheckConstraint(
            "original_language IN ('en', 'ar')", name=op.f("ck_content_items_language")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'ingested', 'processing', 'needs_review', 'published', 'rejected', 'archived')",
            name=op.f("ck_content_items_content_status"),
        ),
        sa.CheckConstraint(
            "importance IS NULL OR importance BETWEEN 1 AND 5",
            name=op.f("ck_content_items_importance_range"),
        ),
        sa.CheckConstraint(
            "title_en IS NOT NULL OR title_ar IS NOT NULL", name=op.f("ck_content_items_has_title")
        ),
        sa.CheckConstraint("view_count >= 0", name=op.f("ck_content_items_view_count_nonneg")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["app.categories.id"],
            name=op.f("fk_content_items_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["app.sources.id"],
            name=op.f("fk_content_items_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_items")),
        sa.UniqueConstraint("content_type", "slug", name="uq_content_items_type_slug"),
        sa.UniqueConstraint("url_hash", name=op.f("uq_content_items_url_hash")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_content_items_category_id"),
        "content_items",
        ["category_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_content_items_source_id"),
        "content_items",
        ["source_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_content_items_featured",
        "content_items",
        ["content_type", sa.literal_column("published_at DESC")],
        unique=False,
        schema="app",
        postgresql_where=sa.text("is_featured AND status = 'published'"),
    )
    op.create_index(
        "ix_content_items_listing",
        "content_items",
        ["content_type", "status", sa.literal_column("published_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_content_items_title_ar_trgm",
        "content_items",
        ["title_ar"],
        unique=False,
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"title_ar": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_content_items_title_en_trgm",
        "content_items",
        ["title_en"],
        unique=False,
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"title_en": "gin_trgm_ops"},
    )
    op.create_table(
        "user_interests",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=4, scale=3), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("weight BETWEEN 0 AND 1", name=op.f("ck_user_interests_weight_range")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["app.categories.id"],
            name=op.f("fk_user_interests_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_user_interests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "category_id", name=op.f("pk_user_interests")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_user_interests_category_id"),
        "user_interests",
        ["category_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=32), server_default="en", nullable=False),
        sa.Column("theme", sa.String(length=32), server_default="system", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("email_digest", sa.String(length=32), server_default="off", nullable=False),
        sa.Column("notify_deadlines", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "notify_topic_updates", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email_digest IN ('off', 'daily', 'weekly')",
            name=op.f("ck_user_preferences_digest_frequency"),
        ),
        sa.CheckConstraint("language IN ('en', 'ar')", name=op.f("ck_user_preferences_language")),
        sa.CheckConstraint(
            "theme IN ('light', 'dark', 'system')", name=op.f("ck_user_preferences_theme")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
        schema="app",
    )
    op.create_table(
        "ai_tools",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("website_url", sa.Text(), nullable=False),
        sa.Column("pricing", sa.String(length=32), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column(
            "platforms",
            sa.ARRAY(sa.String(length=40)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("has_api", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("repository_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pricing IN ('free', 'freemium', 'paid', 'open_source', 'enterprise')",
            name=op.f("ck_ai_tools_tool_pricing"),
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_ai_tools_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_id", name=op.f("pk_ai_tools")),
        schema="app",
    )
    op.create_table(
        "articles",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("reading_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("body_retained_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("reading_minutes > 0", name=op.f("ck_articles_reading_minutes_pos")),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_articles_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_id", name=op.f("pk_articles")),
        schema="app",
    )
    op.create_table(
        "content_authors",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 1", name=op.f("ck_content_authors_position_pos")),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["app.authors.id"],
            name=op.f("fk_content_authors_author_id_authors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_content_authors_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_id", "author_id", name=op.f("pk_content_authors")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_content_authors_author_id"),
        "content_authors",
        ["author_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "content_tags",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("origin", sa.String(length=32), server_default="editor", nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin IN ('editor', 'ai', 'source')", name=op.f("ck_content_tags_tag_origin")
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_content_tags_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_content_tags_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["app.tags.id"],
            name=op.f("fk_content_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_id", "tag_id", name=op.f("pk_content_tags")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_content_tags_tag_id"), "content_tags", ["tag_id"], unique=False, schema="app"
    )
    op.create_table(
        "courses",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=False),
        sa.Column("level", sa.String(length=32), server_default="all_levels", nullable=False),
        sa.Column("duration_hours", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("duration_label_en", sa.String(length=100), nullable=True),
        sa.Column("duration_label_ar", sa.String(length=100), nullable=True),
        sa.Column("instruction_language_en", sa.String(length=100), nullable=True),
        sa.Column("instruction_language_ar", sa.String(length=100), nullable=True),
        sa.Column("is_free", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("has_certificate", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("enrollment_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('beginner', 'intermediate', 'advanced', 'all_levels')",
            name=op.f("ck_courses_course_level"),
        ),
        sa.CheckConstraint(
            "duration_hours IS NULL OR duration_hours > 0", name=op.f("ck_courses_duration_pos")
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_courses_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_id", name=op.f("pk_courses")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_courses_is_free"), "courses", ["is_free"], unique=False, schema="app"
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("chunk_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("chunk_text", sa.Text(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind = 'chunk' OR chunk_index = 0", name=op.f("ck_embeddings_document_single_row")
        ),
        sa.CheckConstraint(
            "kind IN ('document', 'chunk')", name=op.f("ck_embeddings_embedding_kind")
        ),
        sa.CheckConstraint("language IN ('en', 'ar')", name=op.f("ck_embeddings_language")),
        sa.CheckConstraint("chunk_index >= 0", name=op.f("ck_embeddings_chunk_index_nonneg")),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_embeddings_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
        sa.UniqueConstraint(
            "content_id", "model", "kind", "chunk_index", name="uq_embeddings_content_chunk"
        ),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_embeddings_content_id"),
        "embeddings",
        ["content_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_embeddings_vector_hnsw",
        "embeddings",
        ["embedding"],
        unique=False,
        schema="app",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "error_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("component", sa.String(length=50), nullable=False),
        sa.Column("error_type", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("collection_job_id", sa.Uuid(), nullable=True),
        sa.Column("content_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "severity IN ('warning', 'error', 'critical')", name=op.f("ck_error_logs_severity")
        ),
        sa.ForeignKeyConstraint(
            ["collection_job_id"],
            ["app.collection_jobs.id"],
            name=op.f("fk_error_logs_collection_job_id_collection_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_error_logs_content_id_content_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_error_logs")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_error_logs_collection_job_id"),
        "error_logs",
        ["collection_job_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_error_logs_content_id"),
        "error_logs",
        ["content_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_error_logs_component_recent",
        "error_logs",
        ["component", sa.literal_column("occurred_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_error_logs_occurred_at",
        "error_logs",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_error_logs_unresolved",
        "error_logs",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
        schema="app",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_table(
        "learning_path_steps",
        sa.Column("path_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("title_en", sa.String(length=200), nullable=False),
        sa.Column("title_ar", sa.String(length=200), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 1", name=op.f("ck_learning_path_steps_position_pos")),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["app.content_items.id"],
            name=op.f("fk_learning_path_steps_course_id_content_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["app.learning_paths.id"],
            name=op.f("fk_learning_path_steps_path_id_learning_paths"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_path_steps")),
        sa.UniqueConstraint("path_id", "position", name="uq_learning_path_steps_position"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_learning_path_steps_course_id"),
        "learning_path_steps",
        ["course_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("content_id", sa.Uuid(), nullable=True),
        sa.Column("title_en", sa.String(length=200), nullable=False),
        sa.Column("title_ar", sa.String(length=200), nullable=True),
        sa.Column("body_en", sa.Text(), nullable=True),
        sa.Column("body_ar", sa.Text(), nullable=True),
        sa.Column("link_path", sa.String(length=300), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("emailed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('deadline_reminder', 'topic_update', 'daily_brief', 'system')",
            name=op.f("ck_notifications_notification_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_notifications_content_id_content_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_notifications_content_id"),
        "notifications",
        ["content_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_notifications_user_recent",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_notifications_user_unread",
        "notifications",
        ["user_id"],
        unique=False,
        schema="app",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.create_table(
        "opportunities",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_type", sa.String(length=32), nullable=False),
        sa.Column("organization", sa.String(length=200), nullable=False),
        sa.Column("location_en", sa.String(length=200), nullable=True),
        sa.Column("location_ar", sa.String(length=200), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("is_remote", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("eligibility_en", sa.Text(), nullable=True),
        sa.Column("eligibility_ar", sa.Text(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("apply_url", sa.Text(), nullable=True),
        sa.Column("funding_en", sa.Text(), nullable=True),
        sa.Column("funding_ar", sa.Text(), nullable=True),
        sa.Column("employment_type", sa.String(length=32), nullable=True),
        sa.Column("seniority", sa.String(length=50), nullable=True),
        sa.Column("salary_text", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "employment_type IN ('full_time', 'part_time', 'contract', 'temporary', 'internship')",
            name=op.f("ck_opportunities_employment_type"),
        ),
        sa.CheckConstraint(
            "opportunity_type IN ('scholarship', 'fellowship', 'internship', 'job', 'competition', 'hackathon', 'bootcamp', 'research')",
            name=op.f("ck_opportunities_opportunity_type"),
        ),
        sa.CheckConstraint(
            "starts_at IS NULL OR ends_at IS NULL OR starts_at <= ends_at",
            name=op.f("ck_opportunities_dates_order"),
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_opportunities_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_id", name=op.f("pk_opportunities")),
        schema="app",
    )
    op.create_index(
        "ix_opportunities_type_deadline",
        "opportunities",
        ["opportunity_type", "deadline_at"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "papers",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("arxiv_id", sa.String(length=32), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column(
            "subject_areas",
            sa.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("code_url", sa.Text(), nullable=True),
        sa.Column("venue", sa.String(length=200), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("full_text_extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("license", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_papers_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("content_id", name=op.f("pk_papers")),
        sa.UniqueConstraint("arxiv_id", name=op.f("uq_papers_arxiv_id")),
        sa.UniqueConstraint("doi", name=op.f("uq_papers_doi")),
        schema="app",
    )
    op.create_table(
        "processing_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("content_id", sa.Uuid(), nullable=True),
        sa.Column("collection_job_id", sa.Uuid(), nullable=True),
        sa.Column("step", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('started', 'succeeded', 'failed', 'skipped')",
            name=op.f("ck_processing_logs_step_status"),
        ),
        sa.CheckConstraint(
            "step IN ('fetch', 'extract', 'deduplicate', 'classify', 'summarize', 'translate', 'embed', 'publish')",
            name=op.f("ck_processing_logs_processing_step"),
        ),
        sa.CheckConstraint(
            "cost_usd IS NULL OR cost_usd >= 0", name=op.f("ck_processing_logs_cost_nonneg")
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_processing_logs_input_tokens_nonneg"),
        ),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_processing_logs_output_tokens_nonneg"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_job_id"],
            ["app.collection_jobs.id"],
            name=op.f("fk_processing_logs_collection_job_id_collection_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_processing_logs_content_id_content_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_logs")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_processing_logs_collection_job_id"),
        "processing_logs",
        ["collection_job_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_processing_logs_content_recent",
        "processing_logs",
        ["content_id", sa.literal_column("created_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_processing_logs_created_at",
        "processing_logs",
        ["created_at"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_processing_logs_step_recent",
        "processing_logs",
        ["step", "status", sa.literal_column("created_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_table(
        "saved_items",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_saved_items_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
            name=op.f("fk_saved_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "content_id", name=op.f("pk_saved_items")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_saved_items_content_id"),
        "saved_items",
        ["content_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "ix_saved_items_user_recent",
        "saved_items",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        schema="app",
    )
    op.create_table(
        "ai_classifications",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_relevant", sa.Boolean(), nullable=False),
        sa.Column("suggested_category_id", sa.Uuid(), nullable=True),
        sa.Column("importance", sa.SmallInteger(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("processing_log_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_ai_classifications_confidence_range"),
        ),
        sa.CheckConstraint(
            "importance IS NULL OR importance BETWEEN 1 AND 5",
            name=op.f("ck_ai_classifications_importance_range"),
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_ai_classifications_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["processing_log_id"],
            ["app.processing_logs.id"],
            name=op.f("fk_ai_classifications_processing_log_id_processing_logs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["suggested_category_id"],
            ["app.categories.id"],
            name=op.f("fk_ai_classifications_suggested_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_classifications")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_ai_classifications_content_id"),
        "ai_classifications",
        ["content_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_ai_classifications_processing_log_id"),
        "ai_classifications",
        ["processing_log_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "uq_ai_classifications_current",
        "ai_classifications",
        ["content_id"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "ai_summaries",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("tldr", sa.Text(), nullable=True),
        sa.Column(
            "key_points",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("why_it_matters", sa.Text(), nullable=True),
        sa.Column(
            "sections",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("processing_log_id", sa.BigInteger(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('article_brief', 'paper_analysis', 'short')",
            name=op.f("ck_ai_summaries_summary_kind"),
        ),
        sa.CheckConstraint("language IN ('en', 'ar')", name=op.f("ck_ai_summaries_language")),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_ai_summaries_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["processing_log_id"],
            ["app.processing_logs.id"],
            name=op.f("fk_ai_summaries_processing_log_id_processing_logs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["app.users.id"],
            name=op.f("fk_ai_summaries_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_summaries")),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_ai_summaries_content_id"),
        "ai_summaries",
        ["content_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_ai_summaries_processing_log_id"),
        "ai_summaries",
        ["processing_log_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        "uq_ai_summaries_current",
        "ai_summaries",
        ["content_id", "kind", "language"],
        unique=True,
        schema="app",
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "daily_briefs",
        sa.Column("brief_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="draft", nullable=False),
        sa.Column("headline_en", sa.String(length=300), nullable=False),
        sa.Column("headline_ar", sa.String(length=300), nullable=True),
        sa.Column("intro_en", sa.Text(), nullable=True),
        sa.Column("intro_ar", sa.Text(), nullable=True),
        sa.Column("signal_en", sa.Text(), nullable=True),
        sa.Column("signal_ar", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("processing_log_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_daily_briefs_brief_status"),
        ),
        sa.ForeignKeyConstraint(
            ["processing_log_id"],
            ["app.processing_logs.id"],
            name=op.f("fk_daily_briefs_processing_log_id_processing_logs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_briefs")),
        sa.UniqueConstraint("brief_date", name=op.f("uq_daily_briefs_brief_date")),
        schema="app",
    )
    op.create_table(
        "daily_brief_items",
        sa.Column("brief_id", sa.Uuid(), nullable=False),
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("blurb_en", sa.Text(), nullable=True),
        sa.Column("blurb_ar", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("position >= 1", name=op.f("ck_daily_brief_items_position_pos")),
        sa.ForeignKeyConstraint(
            ["brief_id"],
            ["app.daily_briefs.id"],
            name=op.f("fk_daily_brief_items_brief_id_daily_briefs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["app.content_items.id"],
            name=op.f("fk_daily_brief_items_content_id_content_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_brief_items")),
        sa.UniqueConstraint("brief_id", "content_id", name="uq_daily_brief_items_content"),
        sa.UniqueConstraint("brief_id", "position", name="uq_daily_brief_items_position"),
        schema="app",
    )
    op.create_index(
        op.f("ix_app_daily_brief_items_content_id"),
        "daily_brief_items",
        ["content_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_ai_classifications_suggested_category_id"),
        "ai_classifications",
        ["suggested_category_id"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_ai_summaries_reviewed_by"),
        "ai_summaries",
        ["reviewed_by"],
        unique=False,
        schema="app",
    )
    op.create_index(
        op.f("ix_app_daily_briefs_processing_log_id"),
        "daily_briefs",
        ["processing_log_id"],
        unique=False,
        schema="app",
    )
    # ### end Alembic commands ###
    _add_updated_at_triggers_and_rls()


def downgrade() -> None:
    # Triggers are dropped together with their tables. Extensions are left
    # installed because other schemas (e.g. Supabase's) may use them.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_app_ai_classifications_suggested_category_id"),
        table_name="ai_classifications",
        schema="app",
    )
    op.drop_index(op.f("ix_app_ai_summaries_reviewed_by"), table_name="ai_summaries", schema="app")
    op.drop_index(
        op.f("ix_app_daily_briefs_processing_log_id"), table_name="daily_briefs", schema="app"
    )
    op.drop_index(
        op.f("ix_app_daily_brief_items_content_id"), table_name="daily_brief_items", schema="app"
    )
    op.drop_table("daily_brief_items", schema="app")
    op.drop_table("daily_briefs", schema="app")
    op.drop_index(
        "uq_ai_summaries_current",
        table_name="ai_summaries",
        schema="app",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index(
        op.f("ix_app_ai_summaries_processing_log_id"), table_name="ai_summaries", schema="app"
    )
    op.drop_index(op.f("ix_app_ai_summaries_content_id"), table_name="ai_summaries", schema="app")
    op.drop_table("ai_summaries", schema="app")
    op.drop_index(
        "uq_ai_classifications_current",
        table_name="ai_classifications",
        schema="app",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index(
        op.f("ix_app_ai_classifications_processing_log_id"),
        table_name="ai_classifications",
        schema="app",
    )
    op.drop_index(
        op.f("ix_app_ai_classifications_content_id"), table_name="ai_classifications", schema="app"
    )
    op.drop_table("ai_classifications", schema="app")
    op.drop_index("ix_saved_items_user_recent", table_name="saved_items", schema="app")
    op.drop_index(op.f("ix_app_saved_items_content_id"), table_name="saved_items", schema="app")
    op.drop_table("saved_items", schema="app")
    op.drop_index("ix_processing_logs_step_recent", table_name="processing_logs", schema="app")
    op.drop_index("ix_processing_logs_created_at", table_name="processing_logs", schema="app")
    op.drop_index("ix_processing_logs_content_recent", table_name="processing_logs", schema="app")
    op.drop_index(
        op.f("ix_app_processing_logs_collection_job_id"), table_name="processing_logs", schema="app"
    )
    op.drop_table("processing_logs", schema="app")
    op.drop_table("papers", schema="app")
    op.drop_index("ix_opportunities_type_deadline", table_name="opportunities", schema="app")
    op.drop_table("opportunities", schema="app")
    op.drop_index(
        "ix_notifications_user_unread",
        table_name="notifications",
        schema="app",
        postgresql_where=sa.text("read_at IS NULL"),
    )
    op.drop_index("ix_notifications_user_recent", table_name="notifications", schema="app")
    op.drop_index(op.f("ix_app_notifications_content_id"), table_name="notifications", schema="app")
    op.drop_table("notifications", schema="app")
    op.drop_index(
        op.f("ix_app_learning_path_steps_course_id"), table_name="learning_path_steps", schema="app"
    )
    op.drop_table("learning_path_steps", schema="app")
    op.drop_index(
        "ix_error_logs_unresolved",
        table_name="error_logs",
        schema="app",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_index("ix_error_logs_occurred_at", table_name="error_logs", schema="app")
    op.drop_index("ix_error_logs_component_recent", table_name="error_logs", schema="app")
    op.drop_index(op.f("ix_app_error_logs_content_id"), table_name="error_logs", schema="app")
    op.drop_index(
        op.f("ix_app_error_logs_collection_job_id"), table_name="error_logs", schema="app"
    )
    op.drop_table("error_logs", schema="app")
    op.drop_index(
        "ix_embeddings_vector_hnsw",
        table_name="embeddings",
        schema="app",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_app_embeddings_content_id"), table_name="embeddings", schema="app")
    op.drop_table("embeddings", schema="app")
    op.drop_index(op.f("ix_app_courses_is_free"), table_name="courses", schema="app")
    op.drop_table("courses", schema="app")
    op.drop_index(op.f("ix_app_content_tags_tag_id"), table_name="content_tags", schema="app")
    op.drop_table("content_tags", schema="app")
    op.drop_index(
        op.f("ix_app_content_authors_author_id"), table_name="content_authors", schema="app"
    )
    op.drop_table("content_authors", schema="app")
    op.drop_table("articles", schema="app")
    op.drop_table("ai_tools", schema="app")
    op.drop_table("user_preferences", schema="app")
    op.drop_index(
        op.f("ix_app_user_interests_category_id"), table_name="user_interests", schema="app"
    )
    op.drop_table("user_interests", schema="app")
    op.drop_index(
        "ix_content_items_title_en_trgm",
        table_name="content_items",
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"title_en": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_content_items_title_ar_trgm",
        table_name="content_items",
        schema="app",
        postgresql_using="gin",
        postgresql_ops={"title_ar": "gin_trgm_ops"},
    )
    op.drop_index("ix_content_items_listing", table_name="content_items", schema="app")
    op.drop_index(
        "ix_content_items_featured",
        table_name="content_items",
        schema="app",
        postgresql_where=sa.text("is_featured AND status = 'published'"),
    )
    op.drop_index(op.f("ix_app_content_items_source_id"), table_name="content_items", schema="app")
    op.drop_index(
        op.f("ix_app_content_items_category_id"), table_name="content_items", schema="app"
    )
    op.drop_table("content_items", schema="app")
    op.drop_index("ix_collection_jobs_status_recent", table_name="collection_jobs", schema="app")
    op.drop_index("ix_collection_jobs_source_recent", table_name="collection_jobs", schema="app")
    op.drop_table("collection_jobs", schema="app")
    op.drop_index("uq_users_email_lower", table_name="users", schema="app")
    op.drop_table("users", schema="app")
    op.drop_table("tags", schema="app")
    op.drop_index("ix_sources_active_kind", table_name="sources", schema="app")
    op.drop_table("sources", schema="app")
    op.drop_table("learning_paths", schema="app")
    op.drop_index("ix_categories_type_sort", table_name="categories", schema="app")
    op.drop_index(op.f("ix_app_categories_parent_id"), table_name="categories", schema="app")
    op.drop_table("categories", schema="app")
    op.drop_table("authors", schema="app")
    # ### end Alembic commands ###
