import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Search, X } from "lucide-react";
import { Navbar } from "./Navbar";
import { Sidebar } from "./Sidebar";
import { Button } from "@/components/ui/button";
import { allNews, text } from "@/data/mockNews";
import { useApp } from "@/contexts/AppContext";
import { Link } from "@tanstack/react-router";
export function AppShell({children}:{children:ReactNode}){const {language}=useApp();const [collapsed,setCollapsed]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState("");useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearchOpen(true)}if(e.key==="Escape")setSearchOpen(false)};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener)},[]);const filtered=useMemo(()=>allNews.filter(a=>`${text(a.title,language)} ${text(a.summary,language)}`.toLowerCase().includes(query.toLowerCase())),[query,language]);return <div className="min-h-screen bg-background text-foreground"><Navbar onMenu={()=>setMobileOpen(true)} onSearch={()=>setSearchOpen(true)}/><div className="flex h-[calc(100vh-4rem)]"><Sidebar collapsed={collapsed} onCollapse={()=>setCollapsed(v=>!v)} mobileOpen={mobileOpen} onMobileClose={()=>setMobileOpen(false)}/><main className="min-w-0 flex-1 overflow-y-auto">{children}</main></div>{searchOpen&&<div className="fixed inset-0 z-[60] bg-overlay/70 px-4 pt-[12vh] backdrop-blur-sm" onMouseDown={()=>setSearchOpen(false)}><div className="mx-auto max-w-2xl overflow-hidden rounded-lg border border-border bg-popover shadow-modal" onMouseDown={e=>e.stopPropagation()}><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-border px-4"><Search className="text-muted-foreground"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={language==="ar"?"ابحث في الأخبار والأبحاث…":"Search news and research…"} className="h-14 min-w-0 bg-transparent text-sm outline-none"/><Button size="icon" variant="ghost" onClick={()=>setSearchOpen(false)}><X/></Button></div><div className="max-h-[52vh] overflow-y-auto p-2">{filtered.map(item=><Link key={item.id} to="/article/$id" params={{id:item.id}} className="block rounded-md px-3 py-3 hover:bg-accent" onClick={()=>setSearchOpen(false)}><span className="text-[10px] font-bold uppercase text-primary">{text(item.category,language)}</span><p className="mt-1 text-sm font-semibold">{text(item.title,language)}</p></Link>)}</div></div></div>}</div>}
