import { Eye, MessageCircle } from "lucide-react";
import type { NewsItem } from "@/data/mockNews";
import { CategoryBadge } from "./CategoryBadge";
import { SourceBadge } from "./SourceBadge";
import { SaveButton } from "./SaveButton";
import { ShareButton } from "./ShareButton";

export function FeaturedNewsCard({ item, saved, onSave, onShare }: { item: NewsItem; saved: boolean; onSave: () => void; onShare: () => void }) {
  return <article className="overflow-hidden rounded-lg border border-border bg-card shadow-card"><div className="relative aspect-[16/9] overflow-hidden bg-muted sm:aspect-[16/8]"><img src={item.image} alt="AI researchers examining a multimodal reasoning system" width={item.imageWidth} height={item.imageHeight} className="h-full w-full object-cover transition-transform duration-700 hover:scale-[1.015]" /><div className="absolute left-4 top-4 rounded-full bg-overlay px-3 py-1.5 text-[10px] font-bold uppercase tracking-widest text-overlay-foreground backdrop-blur">Lead story</div></div><div className="p-5 sm:p-6"><div className="mb-4 flex flex-wrap items-center gap-3"><CategoryBadge>{item.category}</CategoryBadge><SourceBadge source={item.source} /><span className="text-xs text-muted-foreground">{item.time} · {item.readTime}</span></div><h2 className="max-w-4xl text-2xl font-bold leading-tight tracking-tight text-foreground sm:text-4xl">{item.title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground sm:text-base">{item.summary}</p><div className="mt-5 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-t border-border pt-4"><div className="flex min-w-0 items-center gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Eye className="h-3.5 w-3.5" />{item.views}</span><span className="flex items-center gap-1.5"><MessageCircle className="h-3.5 w-3.5" />{item.comments}</span></div><div className="flex shrink-0 items-center gap-2"><SaveButton saved={saved} onToggle={onSave} /><ShareButton onShare={onShare} compact /></div></div></div></article>;
}