import { Link } from "@tanstack/react-router";
import { Eye, MessageCircle } from "lucide-react";
import type { NewsItem } from "@/data/mockNews";
import { text } from "@/data/mockNews";
import { CategoryBadge } from "./CategoryBadge";
import { SourceBadge } from "./SourceBadge";
import { SaveButton } from "./SaveButton";
import { ShareButton } from "./ShareButton";
import { useApp } from "@/contexts/AppContext";
export function FeaturedNewsCard({item}:{item:NewsItem}){const {language,isSaved,toggleSaved,share}=useApp();return <article className="overflow-hidden rounded-lg border border-border bg-card shadow-card"><Link to="/article/$id" params={{id:item.id}} className="block"><div className="relative aspect-[16/9] overflow-hidden bg-muted sm:aspect-[16/8]"><img src={item.image} alt="" width={item.imageWidth} height={item.imageHeight} className="h-full w-full object-cover transition-transform duration-700 hover:scale-[1.015]"/><div className="absolute start-4 top-4 rounded-full bg-overlay px-3 py-1.5 text-[10px] font-bold uppercase text-overlay-foreground backdrop-blur">{language==="ar"?"القصة الرئيسية":"Lead story"}</div></div></Link><div className="p-5 sm:p-6"><div className="mb-4 flex flex-wrap items-center gap-3"><CategoryBadge>{text(item.category,language)}</CategoryBadge><SourceBadge source={item.source}/><span className="text-xs text-muted-foreground">{text(item.updated,language)} · {text(item.readTime,language)}</span></div><Link to="/article/$id" params={{id:item.id}}><h2 className="max-w-4xl text-2xl font-bold leading-tight text-foreground transition-colors hover:text-primary sm:text-4xl">{text(item.title,language)}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground sm:text-base">{text(item.summary,language)}</p></Link><div className="mt-5 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-t border-border pt-4"><div className="flex items-center gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Eye className="h-3.5 w-3.5"/>{item.views}</span><span className="flex items-center gap-1.5"><MessageCircle className="h-3.5 w-3.5"/>{item.comments}</span></div><div className="flex gap-2"><SaveButton saved={isSaved(item.id)} onToggle={()=>toggleSaved(item.id)}/><ShareButton onShare={()=>share(item.id)} compact/></div></div></div></article>}
